//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 TrafficMonitor.rc 使用
//
#define IDD_TRAFFICMONITOR_DIALOG       102
#define IDR_MAINFRAME                   128
#define IDR_MENU1                       130
#define IDD_NETWORK_INFO_DIALOG         131
#define IDD_ABOUTBOX                    133
#define IDD_TASK_BAR_DIALOG             135
#define IDR_TASK_BAR_MENU               137
#define IDD_SKIN_DIALOG                 138
#define IDB_BITMAP1                     140
#define IDD_HISTORY_TRAFFIC_DIALOG      141
#define IDD_DONATE_DIALOG               143
#define IDB_BITMAP2                     145
#define IDB_DONATE_BITMAP               145
#define IDI_NOFITY_ICON                 146
#define IDD_OPTIONS_DIALOG              147
#define IDD_MAIN_WND_SETTINGS_DIALOG    149
#define IDD_TASKBAR_SETTINGS_DIALOG     150
#define IDR_INFO_MENU                   153
#define IDR_MENU2                       154
#define IDR_HISTORY_TRAFFIC_MENU        154
#define IDD_GENERAL_SETTINGS_DIALOG     155
#define IDB_ABOUT_BACKGROUND_HD         157
#define IDI_NOFITY_ICON2                158
#define IDI_NOFITY_ICON3                159
#define IDD_ICON_SELECT_DIALOG          160
#define IDB_NOTIFY_ICON_PREVIEW         162
#define IDD_MAIN_COLOR_DIALOG           163
#define IDD_TASKBAR_COLOR_DIALOG        165
#define IDS_CHECK_UPDATE_FAILD          167
#define IDS_CHECK_UPDATE_ERROR          168
#define IDD_HISTORY_TRAFFIC_LIST_DIALOG 168
#define IDS_UPDATE_AVLIABLE             169
#define IDS_UPDATE_AVLIABLE2            170
#define IDD_HISTORY_TRAFFIC_CALENDAR_DIALOG 170
#define IDS_ALREADY_UPDATED             171
#define IDS_AUTORUN_FAILED_NO_KEY       172
#define IDS_AUTORUN_FAILED_NO_ACCESS    173
#define IDS_AUTORUN_DELETE_FAILED       174
#define IDS_AN_INSTANCE_RUNNING         175
#define IDS_TRAFFIC_USED_TODAY          176
#define IDS_MEMORY_USAGE                177
#define IDS_CPU_USAGE                   178
#define IDS_SEND_EMAIL_TO_ATHOUR        179
#define IDS_GOTO_GITHUB                 180
#define IDS_DONATE_ATHOUR               181
#define IDS_UPLOAD                      182
#define IDS_DOWNLOAD                    183
#define IDS_MEMORY                      184
#define IDS_UPLOAD_DISP                 185
#define IDS_DOWNLOAD_DISP               186
#define IDS_MEMORY_DISP                 187
#define IDS_CONNOT_SAVE_CONFIG_WARNING  188
#define IDS_TRAFFICMONITOR              189
#define IDS_INSUFFICIENT_BUFFER         190
#define IDS_CONNECTION_NUM_CHANGED      191
#define IDS_CONNECTION_NOT_MATCH        192
#define IDS_CONNOT_INSERT_TO_TASKBAR    193
#define IDS_MEMORY_UDAGE_EXCEED         194
#define IDS_NOTIFY                      195
#define IDS_TODAY_TRAFFIC_EXCEED        196
#define IDS_TITLE_ABOUT                 197
#define IDS_TITLE_DONATE                198
#define IDS_TITLE_HISTORY_TRAFFIC       199
#define IDS_TITLE_CONNECTION_DETIAL     200
#define IDS_TITLE_CHANGE_SKIN           201
#define IDS_TITLE_OPTION                202
#define IDS_TITLE_CHANGE_ICON           203
#define IDS_DATE                        204
#define IDS_TRAFFIC_USED                205
#define IDS_FIGURE                      206
#define IDS_DEFAULT_ICON                207
#define IDS_ICON                        208
#define IDS_INTERFACE_NAME              209
#define IDS_INTERFACE_DESCRIPTION       210
#define IDS_CONNECTION_TYPE             211
#define IDS_IF_TYPE_OTHER               212
#define IDS_IF_TYPE_ETHERNET_CSMACD     213
#define IDS_IF_TYPE_ISO88025_TOKENRING  214
#define IDS_IF_TYPE_FDDI                215
#define IDS_IF_TYPE_PPP                 216
#define IDS_IF_TYPE_SOFTWARE_LOOPBACK   217
#define IDS_IF_TYPE_ATM                 218
#define IDS_IF_TYPE_IEEE80211           219
#define IDS_IF_TYPE_TUNNEL              220
#define IDS_IF_TYPE_IEEE1394            221
#define IDS_IF_TYPE_IEEE80216_WMAN      222
#define IDS_IF_TYPE_WWANPP              223
#define IDS_IF_TYPE_WWANPP2             224
#define IDS_UNKNOW_CONNECTION           225
#define IDS_SPEED                       226
#define IDS_ADAPTER_PHYSICAL_ADDRESS    227
#define IDS_IP_ADDRESS                  228
#define IDS_SUBNET_MASK                 229
#define IDS_DEFAULT_GATEWAY             230
#define IDS_OPERATIONAL_STATUS          231
#define IDS_IF_OPER_STATUS_NON_OPERATIONAL 232
#define IDS_IF_OPER_STATUS_UNREACHABLE  233
#define IDS_IF_OPER_STATUS_DISCONNECTED 234
#define IDS_IF_OPER_STATUS_CONNECTING   235
#define IDS_IF_OPER_STATUS_CONNECTED    236
#define IDS_IF_OPER_STATUS_OPERATIONAL  237
#define IDS_UNKNOW_STATUS               238
#define IDS_BYTES_RECEIVED              239
#define IDS_BYTES_SENT                  240
#define IDS_BYTES_RECEIVED_SINCE_START  241
#define IDS_BYTES_SENT_SINCE_START      242
#define IDS_PROGRAM_ELAPSED_TIME        243
#define IDS_HOUR_MINUTE_SECOND          244
#define IDS_INTERNET_IP_ADDRESS         245
#define IDS_GET_FAILED                  246
#define IDS_ITEM                        247
#define IDS_VALUE                       248
#define IDS_COPY_TO_CLIPBOARD_FAILED    249
#define IDS_SKIN_AUTHOUR                250
#define IDS_OVERWRITE_FONT_TEXT_WARNING 251
#define IDS_OVERWRITE_FONT_WARNING      252
#define IDS_OVERWRITE_TEXT_WARNING      253
#define IDS_SPEED_SHORT_MODE_TIP        254
#define IDS_AUTO                        255
#define IDS_FIXED_AS                    256
#define IDS_OPEN_CONNECTION_DETIAL      257
#define IDS_OPEN_HISTORICAL_TRAFFIC     258
#define IDS_SHOW_HIDE_MORE_INFO         259
#define IDS_SHOW_HIDE_CPU_MEMORY        260
#define IDS_OPEN_OPTION_SETTINGS        261
#define IDS_OPEN_TASK_MANAGER           262
#define IDS_CHANGE_SKIN                 263
#define IDS_NONE                        264
#define IDS_FONT_SIZE_WARNING           265
#define IDS_SAME_TEXT_BACK_COLOR_WARNING 266
#define IDS_SAME_BACK_TEXT_COLOR_WARNING 267
#define IDS_FOLLOWING_SYSTEM            268
#define IDS_LANGUAGE_CHANGE_INFO        269
#define IDS_MAIN_WINDOW_SETTINGS        270
#define IDS_TASKBAR_WINDOW_SETTINGS     271
#define IDS_GENERAL_SETTINGS            272
#define IDS_MICROSOFT_YAHEI             273
#define IDS_ACQUIRING                   274
#define IDS_DEFAULT_FONT                275
#define IDS_LIST_VIEW                   276
#define IDS_CALENDAR_VIEW               277
#define IDS_MONDAY                      278
#define IDS_TUESDAY                     279
#define IDS_WEDNESDAY                   280
#define IDS_THURSDAY                    281
#define IDS_FRIDAY                      282
#define IDS_SATURDAY                    283
#define IDS_SUNDAY                      284
#define IDS_CURRENT_MONTH_TOTAL_TRAFFIC 285
#define IDS_TRAFFIC_USED1               286
#define IDS_LANGUAGE_CODE               287
#define IDS_CONNOT_INSERT_TO_TASKBAR_ERROR_LOG 288
#define IDS_NO_CONNECTION               289
#define IDS_SEND_EMAIL_TO_TRANSLATOR    290
#define IDS_CONTACT_TRANSLATOR          290
#define IDR_TEXT2                       290
#define IDR_TEXT                        290
#define IDS_THANKS_DONORS               291
#define IDS_GET_URL_ERROR_LOG_INFO      292
#define IDS_SHOW_ALL_INFO_TIP           293
#define IDD_DIALOG1                     293
#define IDD_MESSAGE_DIALOG              293
#define IDR_ACKNOWLEDGEMENT_TEXT        294
#define IDS_CFG_DIR_CHANGED_INFO        294
#define IDS_DOUBLE_CLICK_TO_ACQUIRE     295
#define IDS_ERROR1                      296
#define IDS_ERROR_MESSAGE               297
#define IDS_CRASH_INFO                  298
#define IDS_TITLE_ACKNOWLEDGEMENT       299
#define IDI_NOFITY_ICON4                299
#define IDS_SAVE_DEFAULT_STYLE_INQUIRY  300
#define IDS_SPECIFIC_APP                301
#define IDB_NOTIFY_ICON_PREVIEW_LIGHT   302
#define IDS_EXE_FILTER                  302
#define IDS_PRESET                      303
#define IDS_LIGHT_MODE                  304
#define IDB_BITMAP3                     305
#define IDB_DONATE_WECHAT               305
#define IDS_AUTO_ADAPT_TIP_INFO         305
#define IDD_ATUO_ADAPT_SETTING_DIALOG   306
#define IDS_WITHOUT_TEMPERATURE         306
#define IDS_MOUSE_PENETRATE_TIP_INFO    307
#define IDS_HISTORY_TRAFFIC_LOST_ERROR_LOG 308
#define IDS_LEGEND                      309
#define IDR_LICENSE                     310
#define IDS_LICENSE_EXPLAIN             310
#define IDS_LICENSE                     311
#define IDI_EXIT                        311
#define IDI_HELP                        312
#define IDS_DAY_VIEW                    312
#define IDI_INFO                        313
#define IDS_MONTH_VIEW                  313
#define IDI_LOCK                        314
#define IDS_QUARTER_VIEW                314
#define IDI_SETTINGS                    315
#define IDS_YEAR_VIEW                   315
#define IDI_STATISTICS                  316
#define IDS_LINEAR_SCALE                316
#define IDI_CLOSE                       317
#define IDS_LOG_SCALE                   317
#define IDI_PIN                         318
#define IDS_CPU_TEMPERATURE             318
#define IDI_SKIN                        319
#define IDS_GPU_TEMPERATURE             319
#define IDI_CONNECTION                  320
#define IDS_HDD_TEMPERATURE             320
#define IDI_MOUSE                       321
#define IDS_MAINBOARD_TEMPERATURE       321
#define IDI_MAIN_WINDOW                 322
#define IDS_GPU_DISP                    322
#define IDI_TASKBAR_WINDOW              323
#define IDS_HDD_DISP                    323
#define IDI_NOTIFY                      324
#define IDS_MAINBOARD_DISP              324
#define IDI_MORE                        325
#define IDS_CPU_TEMPERATURE_EXCEED      325
#define IDI_ITEM                        326
#define IDS_GPU_TEMPERATURE_EXCEED      326
#define IDI_FUNCTION                    327
#define IDS_HDD_TEMPERATURE_EXCEED      327
#define IDI_NOTIFY_ICON5                328
#define IDS_MBD_TEMPERATURE_EXCEED      328
#define IDD_DISPLAY_TEXT_SETTINGS_DIALOG 329
#define IDS_MUSICPLAYER2_DESCRIPTION    329
#define IDR_COMPILE_TIME                329
#define IDS_SIMPLENOTEPAD_DESCRIPTION   330
#define IDD_SELECT_ORDER_DIALOG         330
#define IDS_COLOR                       331
#define IDS_COLOR_LABEL                 332
#define IDD_PLUGIN_MANAGER_DIALOG       332
#define IDS_COLOR_VALUE                 333
#define IDS_GPU_USAGE                   334
#define IDI_PLUGINS                     334
#define IDS_IF_OPER_STATUS_UP           335
#define IDR_MENU3                       335
#define IDR_PLUGIN_MANAGER_MENU         335
#define IDS_IF_OPER_STATUS_DOWN         336
#define IDI_TASK_MANAGER                336
#define IDS_IF_OPER_STATUS_DORMANT      337
#define IDD_APP_ALREAD_RUNING_DIALOG    337
#define IDS_GOTO_GITEE                  338
#define IDS_USAGE_PERCENTAGE            339
#define IDD_SELECT_CONNECTIONS_DIALOG   339
#define IDS_MEMORY_USED                 340
#define IDD_TASK_BAR_DIALOG_NOREDIRECTIONBITMAP 340
#define IDS_MEMORY_AVAILABLE            341
#define IDD_SKIN_AUTO_ADAPT_DLG         341
#define IDS_DOTNET_NOT_INSTALLED_TIP    342
#define IDS_VERSION_UPDATE              343
#define IDI_ICON1                       343
#define IDI_PLUGIN_DISABLED             343
#define IDS_AVREAGE_TEMPERATURE         344
#define IDD_WIN11_TASKBAR_SETTING_DLG   344
#define IDS_HARDWARE_MONITOR_WARNING    345
#define IDS_HARDWARE_MONITOR_WARNING2   346
#define IDS_HDD_USAGE                   347
#define IDS_FILE_NAME                   348
#define IDS_STATUS                      349
#define IDS_PLUGIN_LOAD_SUCCEED         350
#define IDS_PLUGIN_MODULE_LOAD_FAILED   351
#define IDS_PLUGIN_FUNCTION_GET_FAILED  352
#define IDS_PLUGIN_INFO                 353
#define IDS_NAME                        354
#define IDS_DESCRIPTION                 355
#define IDS_FILE_PATH                   356
#define IDS_ITEM_NUM                    357
#define IDS_ITEM_NAMES                  358
#define IDS_AUTHOR                      359
#define IDS_COPYRIGHT                   360
#define IDS_PLUGIN_NO_OPTIONS_INFO      361
#define IDS_PLUGIN_NAME                 362
#define IDS_DISABLED                    363
#define IDS_RESTART_TO_APPLY_CHANGE_INFO 364
#define IDS_VERSION                     365
#define IDS_DISP_ITEM_ID                366
#define IDS_PLUGIN_API_VERSION          367
#define IDS_WEEK_VIEW                   368
#define IDS_WEEK_NUM                    369
#define IDS_URL                         370
#define IDS_PLUGIN_VERSION_NOT_SUPPORT  371
#define IDS_MODIFY_PRESET               372
#define IDS_SELECT_AT_LEASE_ONE_WARNING 373
#define IDS_AUTO_SAVE_TO_PRESET_TIP     374
#define IDS_TOTAL_NET_SPEED             375
#define IDS_SHOW_RESOURCE_USAGE_GRAPH_TIP 376
#define IDS_SHOW_NET_SPEED_GRAPH_TIP    377
#define IDS_REFRESH_CONNECTION_LIST     378
#define IDS_HARDWARE_MONITOR_INIT_FAILED 379
#define IDS_HARDWARE_INFO_ACQUIRE_FAILED_ERROR 380
#define IDS_AUTO_RUN_METHOD_REGESTRY    381
#define IDS_AUTO_RUN_METHOD_TASK_SCHEDULE 382
#define IDS_PATH                        383
#define IDS_SET_AUTO_RUN_FAILED_WARNING 384
#define IDS_UPDATE_TASKBARDLG_FAILED_TIP 385
#define IDS_D2DDRAWCOMMON_ERROR_TIP     386
#define IDS_PLUGIN_OPTIONS              387
#define IDS_PLUGIN_DETAILS              388
#define IDC_STATIC_INFO                 1001
#define IDC_STATIC1                     1002
#define IDC_STATIC_DOWN                 1002
#define IDC_STATIC_UP                   1003
#define IDC_STATIC2                     1003
#define IDC_STATIC_DOWN1                1003
#define IDC_STATIC_MEMORY               1004
#define IDC_STATIC3                     1004
#define IDC_STATIC_CPU                  1005
#define IDC_STATIC4                     1005
#define IDC_STATIC_UP1                  1006
#define IDC_STATIC_VERSION              1007
#define IDC_COMBO1                      1008
#define IDC_STATIC_SKIN_S               1009
#define IDC_STATIC_SKIN_L               1010
#define IDC_STATIC_TEXT2                1012
#define IDC_SKIN_INFO                   1013
#define IDC_STATIC_ABOUT                1015
#define IDC_STATIC_MAIL                 1016
#define IDC_LIST1                       1017
#define IDC_INFO_LIST                   1017
#define IDC_INFO_LIST1                  1017
#define IDC_HISTORY_INFO_LIST           1017
#define IDC_STATIC_LICENSE              1017
#define IDC_DONATE_PIC                  1018
#define IDC_FONT_NAME_EDIT              1019
#define IDC_FONT_SIZE_EDIT              1020
#define IDC_STATIC_CHECK_UPDATE         1021
#define IDC_SET_FONT_BUTTON             1021
#define IDC_STATIC_DONATE               1022
#define IDC_TEXT_COLOR_STATIC           1022
#define IDC_UPLOAD_EDIT                 1023
#define IDC_DOWNLOAD_EDIT               1024
#define IDC_CPU_EDIT                    1025
#define IDC_MEMORY_EDIT                 1026
#define IDC_FONT_NAME_EDIT1             1027
#define IDC_FONT_SIZE_EDIT1             1028
#define IDC_SET_FONT_BUTTON1            1029
#define IDC_TEXT_COLOR_STATIC1          1030
#define IDC_UPLOAD_EDIT1                1031
#define IDC_DOWNLOAD_EDIT1              1032
#define IDC_CPU_EDIT1                   1033
#define IDC_MEMORY_EDIT1                1034
#define IDC_TEXT_COLOR_STATIC2          1035
#define IDC_TAB1                        1035
#define IDC_SET_DEFAULT_BUTTON          1036
#define IDC_TEXT_COLOR_STATIC3          1036
#define IDC_SET_COLOR_BUTTON2           1037
#define IDC_TRANSPARENT_COLOR_STATIC    1037
#define IDC_SET_COLOR_BUTTON1           1038
#define IDC_SET_COLOR_BUTTON3           1038
#define IDC_SWITCH_UP_DOWN_CHECK        1039
#define IDC_SWITCH_UP_DOWN_CHECK1       1040
#define IDC_SET_DEFAULT_BUTTON1         1041
#define IDC_FULLSCREEN_HIDE_CHECK       1042
#define IDC_SWITCH_UP_DOWN_CHECK2       1042
#define IDC_SPEED_SHORT_MODE_CHECK      1042
#define IDC_STATIC_GITHUB               1043
#define IDC_SPEED_SHORT_MODE_CHECK2     1043
#define IDC_SET_LIGHT_MODE_BUTTON       1043
#define IDC_CHECK_UPDATE_CHECK          1044
#define IDC_STATIC_GITEE                1044
#define IDC_CHECK_NOW_BUTTON            1045
#define IDC_AUTO_RUN_CHECK              1046
#define IDC_TASKBAR_WND_ON_LEFT_CHECK   1047
#define IDC_HIDE_UNIT_CHECK             1049
#define IDC_UNIT_COMBO                  1050
#define IDC_ICON_PREVIEW                1051
#define IDC_HIDE_PERCENTAGE_CHECK       1051
#define IDC_SKIN_COURSE_STATIC          1052
#define IDC_SKIN_COURSE_STATIC2         1053
#define IDC_SKIN_DOWNLOAD_STATIC        1053
#define IDC_PREVIEW_GROUP_STATIC        1054
#define IDC_NOTIFY_STATIC               1056
#define IDC_ALLOW_SKIN_FONT_CHECK       1057
#define IDC_CHECK2                      1058
#define IDC_ALLOW_SKIN_DISP_STR_CHECK   1058
#define IDC_VALUE_RIGHT_ALIGN_CHECK     1058
#define IDC_ALWAYS_ON_TOP_CHECK         1058
#define IDC_UP_STATIC                   1059
#define IDC_DOWN_STATIC                 1060
#define IDC_UP_VALUE_STATIC             1060
#define IDC_CPU_STATIC                  1061
#define IDC_DWON_LABLE_STATIC           1061
#define IDC_MEMORY_STATIC               1062
#define IDC_DWON_VALUE_STATIC           1062
#define IDC_SPECIFY_EACH_ITEM_COLOR_CHECK 1063
#define IDC_CPU_LABLE_STATIC            1063
#define IDC_CPU_TEMP_STATIC             1063
#define IDC_CPU_VALUE_STATIC            1064
#define IDC_GPU_TEMP_STATIC             1064
#define IDC_MEMORY_LABLE_STATIC         1065
#define IDC_HDD_TEMP_STATIC             1065
#define IDC_UP_STATIC8                  1066
#define IDC_MEMORY_VALUE_STATIC         1066
#define IDC_MEMORY_STATIC2              1066
#define IDC_MBD_TEMP_STATIC             1066
#define IDC_UP_LABLE_STATIC             1067
#define IDC_DOUBLE_CLICK_COMBO          1068
#define IDC_TODAY_TRAFFIC_TIP_CHECK     1069
#define IDC_TODAY_TRAFFIC_TIP_EDIT      1070
#define IDC_MEMORY_USAGE_TIP_CHECK      1071
#define IDC_MEMORY_USAGE_TIP_EDIT       1072
#define IDC_TODAY_TRAFFIC_TIP_COMBO     1073
#define IDC_STATIC_COPYRIGHT            1074
#define IDC_LANGUAGE_COMBO              1075
#define IDC_CPU_TEMP_LABLE_STATIC       1076
#define IDC_CPU_TEMP_TIP_EDIT           1076
#define IDC_YEAR_COMBO                  1077
#define IDC_CPU_TEMP_VALUE_STATIC       1077
#define IDC_GPU_TEMP_TIP_CHECK          1077
#define IDC_MONTH_COMBO                 1078
#define IDC_GPU_TEMP_LABLE_STATIC       1078
#define IDC_GPU_TEMP_TIP_EDIT           1078
#define IDC_PREVIOUS_BUTTON             1079
#define IDC_GPU_TEMP_VALUE_STATIC       1079
#define IDC_NEXT_BUTTON                 1080
#define IDC_OPEN_CONFIG_PATH_BUTTON     1080
#define IDC_HDD_TEMP_LABLE_STATIC       1080
#define IDC_DIGIT_NUMBER_COMBO          1081
#define IDC_HDD_TEMP_VALUE_STATIC       1081
#define IDC_HDD_TIP_EDIT                1081
#define IDC_HORIZONTAL_ARRANGE_CHECK    1082
#define IDC_MAIN_BOARD_TEMP_LABLE_STATIC 1082
#define IDC_MBD_TEMP_TIP_CHECK          1082
#define IDC_PREVIEW_BUTTON              1083
#define IDC_MAIN_BOARD_TEMP_VALUE_STATIC 1083
#define IDC_MBD_TEMP_TIP_EDIT           1083
#define IDC_INDEX_STATIC                1084
#define IDC_STATIC_ACKNOWLEDGEMENT      1085
#define IDC_TRADITIONAL_CHINESE_TRANSLATOR_STATIC 1086
#define IDC_TRANSLATOR_STATIC           1087
#define IDC_SEPARATE_VALUE_UNIT_CHECK   1089
#define IDC_SHOW_STATUS_BAR_CHECK       1090
#define IDC_UNIT_BYTE_RADIO             1091
#define IDC_UNIT_BIT_RADIO              1092
#define IDC_SHOW_ALL_CONNECTION_CHECK   1092
#define IDC_SAVE_TO_APPDATA_RADIO       1093
#define IDC_SAVE_TO_PROGRAM_DIR_RADIO   1094
#define IDC_HELP_EDIT                   1095
#define IDC_INFO_STATIC                 1096
#define IDC_SHOW_TOOL_TIP_CHK           1097
#define IDC_DEFAULT_STYLE_BUTTON        1098
#define IDC_BROWSE_BUTTON               1100
#define IDC_EXE_PATH_EDIT               1101
#define IDC_EXE_PATH_STATIC             1102
#define IDC_TEXT_STATIC                 1103
#define IDC_CM_GRAPH_BAR_RADIO          1104
#define IDC_CM_GRAPH_PLOT_RADIO         1105
#define IDC_USE_CPU_TIME_RADIO          1106
#define IDC_USE_PDH_RADIO               1107
#define IDC_BACKGROUND_TRANSPARENT_CHECK 1108
#define IDC_USE_HARDWARE_MONITOR_RADIO  1108
#define IDC_AUTO_ADAPT_LIGHT_THEME_CHECK 1109
#define IDC_AUTO_ADAPT_SETTINGS_BUTTON  1110
#define IDC_DARK_MODE_DEFAULT_STYLE_COMBO 1111
#define IDC_LIGHT_MODE_DEFAULT_STYLE_COMBO 1112
#define IDC_MENU_BUTTON                 1112
#define IDC_AUTO_ADAPT_CHECK            1113
#define IDC_MONITOR_SPAN_EDIT           1114
#define IDC_VIEW_TYPE_COMBO             1115
#define IDC_VIEW_SCALE_COMBO            1116
#define IDC_HDD_TEMP_TIP_CHECK          1117
#define IDC_AUTO_SET_BACK_COLOR_CHECK   1117
#define IDC_RESTORE_DEFAULT_BUTTON      1118
#define IDC_DISPLAY_TEXT_SETTING_BUTTON 1119
#define IDC_CPU_TEMP_TIP_CHECK          1120
#define IDC_OPENHARDWAREMONITOR_LINK    1122
#define IDC_TINYXML2_LINK               1123
#define IDC_MUSICPLAYER2_LINK           1124
#define IDC_SIMPLENOTEPAD_LINK          1125
#define IDC_GITHUB_RADIO                1126
#define IDC_GITEE_RADIO                 1127
#define IDC_MEMORY_DISPLAY_COMBO        1127
#define IDC_RESTORE_DEFAULT_TIME_SPAN_BUTTON 1128
#define IDC_SELECT_HARD_DISK_COMBO      1129
#define IDC_CPU_CHECK                   1130
#define IDC_GPU_CHECK                   1131
#define IDC_SHOW_DASHED_BOX             1131
#define IDC_HDD_CHECK                   1132
#define IDC_MBD_CHECK                   1133
#define IDC_MOUSE_PENETRATE_CHECK       1133
#define IDC_SELECT_CPU_COMBO            1134
#define IDC_LOCK_WINDOW_POS_CHECK       1134
#define IDC_ALOW_OUT_OF_BORDER_CHECK    1135
#define IDC_MOVE_UP_BUTTON              1136
#define IDC_MOVE_DOWN_BUTTON            1137
#define IDC_SET_ORDER_BUTTON            1137
#define IDC_OPTINS_BUTTON               1139
#define IDC_PLUGIN_MANAGE_BUTTON        1140
#define IDC_PLUGIN_INFO_BUTTON          1141
#define IDC_SHOW_NOTIFY_ICON_CHECK      1142
#define IDC_HDD_STATIC                  1143
#define IDC_HARDWARE_MONITOR_STATIC     1144
#define IDC_SELECT_HDD_STATIC           1145
#define IDC_SELECT_CPU_STATIC           1146
#define IDC_APPLY_BUTTON                1147
#define IDC_TASKBAR_WND_SNAP_CHECK      1148
#define IDC_ITEM_SPACE_EDIT             1149
#define IDC_EXIT_INST_BUTTON            1150
#define IDC_OPEN_SETTINGS_BUTTON        1151
#define IDC_SHOW_HIDE_MAIN_WINDOW_BUTTON 1152
#define IDC_SHOW_HIDE_TASKBAR_WINDOW_BUTTON 1153
#define IDC_PLUGIN_DEV_GUID_STATIC      1153
#define IDC_PLUGIN_DOWNLOAD_STATIC      1154
#define IDC_SELECT_CONNECTIONS_BUTTON   1155
#define IDC_AUTO_SAVE_TO_PRESET_CHECK   1156
#define IDC_SHOW_NET_SPEED_FIGURE_CHECK 1157
#define IDC_NET_SPEED_FIGURE_MAX_VALUE_EDIT 1158
#define IDC_NET_SPEED_FIGURE_MAX_VALUE_UNIT_COMBO 1159
#define IDC_OPEN_PLUGIN_DIR_STATIC      1160
#define IDC_OPEN_SKIN_DIR_STATIC        1161
#define IDC_RESET_AUTO_RUN_BUTTON       1162
#define IDS_CPU_FREQ                    1163
#define IDC_WINDOW_OFFSET_TOP_NEGATIVE_CHECK 1166
#define IDC_WINDOW_OFFSET_TOP_EDIT      1167
#define IDC_VERTICAL_MARGIN_EDIT        1168
#define IDC_WIDTET_WIDTH_EDIT           1168
#define IDC_VERTICAL_MARGIN_NEGATIVE_CHECK 1169
#define IDC_WINDOW_OFFSET_LEFT_EDIT     1169
#define IDC_WINDOW_OFFSET_TOP_EDIT2     1169
#define IDC_DISABLE_D2D                 1170
#define IDC_GDI_RADIO                   1171
#define IDC_D2D_RADIO                   1172
#define IDC_SKIN_AUTO_ADAPT_CHECK       1173
#define IDC_SKIN_AUTO_ADAPT_BUTTON      1174
#define IDC_DARK_MODE_SKIN_COMBO        1175
#define IDC_LIGHT_MODE_SKIN_COMBO       1176
#define IDC_ENABLE_COLOR_EMOJI_CHECK    1177
#define IDC_WIN11_SETTINGS_BUTTON       1178
#define IDC_AVOID_OVERLAP_RIGHT_WIDGETS_CHECK 1179
#define ID_32771                        32771
#define ID_NETWORK_INFO                 32772
#define ID_32773                        32773
#define ID_ALWAYS_ON_TOP                32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_32777                        32777
#define ID_32778                        32778
#define ID_32779                        32779
#define ID_TRANS_100                    32780
#define ID_TRANSPARENCY_100             32781
#define ID_TRANSPARENCY_80              32782
#define ID_TRANSPARENCY_60              32783
#define ID_TRANSPARENCY_40              32784
#define ID_32785                        32785
#define ID_32786                        32786
#define ID_32789                        32789
#define ID_LOCK_WINDOW_POS              32790
#define ID_32791                        32791
#define ID_SHOW_NOTIFY_ICON             32792
#define ID_32793                        32793
#define ID_SHOW_CPU_MEMORY              32794
#define ID_32795                        32795
#define ID_MOUSE_PENETRATE              32796
#define ID_32797                        32797
#define ID_32798                        32798
#define ID_TEXT_COLOR                   32799
#define ID_32800                        32800
#define ID_SHOW_TASK_BAR_WND            32801
#define ID_32802                        32802
#define ID_32803                        32803
#define ID_32804                        32804
#define ID_32805                        32805
#define ID_32806                        32806
#define ID_SET_BACK_COLOR               32807
#define ID_32808                        32808
#define ID_SET_TEXT_COLOR               32809
#define ID_32810                        32810
#define ID_SHOW_CPU_MEMORY2             32811
#define ID_32812                        32812
#define ID_MINMIZE                      32813
#define ID_32814                        32814
#define ID_AUTO_RUN_WHEN_START          32815
#define ID_HIDE_MAIN_WND                32816
#define ID_32817                        32817
#define ID_32818                        32818
#define ID_CHANGE_SKIN                  32819
#define ID_32820                        32820
#define ID_SET_FONT                     32821
#define ID_32822                        32822
#define ID_SET_                         32823
#define ID_SET_FONT2                    32824
#define ID_32825                        32825
#define ID_TRAFFIC_HISTORY              32826
#define ID_32827                        32827
#define ID_32828                        32828
#define ID_OPTIONS                      32829
#define ID_32830                        32830
#define ID_OPTIONS2                     32831
#define ID_32832                        32832
#define ID_COPY_TEXT                    32833
#define ID_32834                        32834
#define ID_32835                        32835
#define ID_USE_LINEAR_SCALE             32836
#define ID_USE_LOG_SCALE                32837
#define ID_32838                        32838
#define ID_CHANGE_NOTIFY_ICON           32839
#define ID_32840                        32840
#define ID_ALOW_OUT_OF_BORDER           32841
#define ID_32842                        32842
#define ID_32843                        32843
#define ID_32844                        32844
#define ID_32845                        32845
#define ID_CHECK_UPDATE                 32846
#define ID_SHOW_MAIN_WND                32847
#define ID_DEFAULT_STYLE1               32848
#define ID_DEFAULT_STYLE_MAX            32857
#define ID_MODIFY_DEFAULT_STYLE1        32858
#define ID_MODIFY_DEFAULT_STYLE_MAX     32867
#define ID_LIGHT_MODE_STYLE             32868
#define ID_SHOW_NET_SPEED               32869
#define ID_FIRST_DAY_OF_WEEK_SUNDAY     32870
#define ID_FIRST_DAY_OF_WEEK_MONDAY     32871
#define ID_CALENDAR_JUMP_TO_TODAY       32872
#define ID_FREQUENTY_ASKED_QUESTIONS    32873
#define ID_CMD_TEST                     32874
#define ID_SHOW_UP_SPEED                32875
#define ID_SHOW_DOWN_SPEED              32876
#define ID_SHOW_CPU_USAGE               32877
#define ID_SHOW_MEMORY_USAGE            32878
#define ID_SHOW_CPU_TEMPERATURE         32879
#define ID_SHOW_GPU_TEMPERATURE         32880
#define ID_SHOW_HDD_TEMPERATURE         32881
#define ID_SHOW_MAIN_BOARD_TEMPERATURE  32882
#define ID_SHOW_GPU                     32883
#define ID_SHOW_HDD                     32884
#define ID_UPDATE_LOG                   32885
#define ID_PLUGIN_MANAGE                32886
#define ID_SHOW_PLUGIN_ITEM_START       32887
#define ID_SHOW_PLUGIN_ITEM_MAX         33140
#define ID_SELETE_CONNECTION            33141
#define ID_SELECT_ALL_CONNECTION        33142
#define ID_SELETE_CONNECTION_MAX        33398
#define ID_PLUGIN_DETAIL                33399
#define ID_PLUGIN_OPTIONS               33400
#define ID_PLUGIN_DISABLE               33401
#define ID_SHOW_TOTAL_SPEED             33402
#define ID_OPEN_TASK_MANAGER            33403
#define ID_REFRESH_CONNECTION_LIST      33404
#define ID_DISPLAY_SETTINGS             33405
#define ID_PLUGIN_DETAIL_TASKBAR        33406
#define ID_PLUGIN_OPTIONS_TASKBAR       33407
#define ID_PLUGIN_COMMAND_START         33408
#define ID_PLUGIN_COMMAND_MAX           33664

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        346
#define _APS_NEXT_COMMAND_VALUE         33665
#define _APS_NEXT_CONTROL_VALUE         1181
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
